// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserAuthenticated user authenticated
//
// swagger:model userAuthenticated
type UserAuthenticated struct {

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this user authenticated
func (m *UserAuthenticated) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserAuthenticated) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserAuthenticated) UnmarshalBinary(b []byte) error {
	var res UserAuthenticated
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
