// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dimsumgurl/noteable-backend/pkg/api/models"
)

// PostLoginOKCode is the HTTP code returned for type PostLoginOK
const PostLoginOKCode int = 200

/*PostLoginOK OK

swagger:response postLoginOK
*/
type PostLoginOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserToken `json:"body,omitempty"`
}

// NewPostLoginOK creates PostLoginOK with default headers values
func NewPostLoginOK() *PostLoginOK {

	return &PostLoginOK{}
}

// WithPayload adds the payload to the post login o k response
func (o *PostLoginOK) WithPayload(payload *models.UserToken) *PostLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post login o k response
func (o *PostLoginOK) SetPayload(payload *models.UserToken) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostLoginUnauthorizedCode is the HTTP code returned for type PostLoginUnauthorized
const PostLoginUnauthorizedCode int = 401

/*PostLoginUnauthorized unauthorized

swagger:response postLoginUnauthorized
*/
type PostLoginUnauthorized struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewPostLoginUnauthorized creates PostLoginUnauthorized with default headers values
func NewPostLoginUnauthorized() *PostLoginUnauthorized {

	return &PostLoginUnauthorized{}
}

// WithPayload adds the payload to the post login unauthorized response
func (o *PostLoginUnauthorized) WithPayload(payload interface{}) *PostLoginUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post login unauthorized response
func (o *PostLoginUnauthorized) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostLoginUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostLoginInternalServerErrorCode is the HTTP code returned for type PostLoginInternalServerError
const PostLoginInternalServerErrorCode int = 500

/*PostLoginInternalServerError internal server error

swagger:response postLoginInternalServerError
*/
type PostLoginInternalServerError struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewPostLoginInternalServerError creates PostLoginInternalServerError with default headers values
func NewPostLoginInternalServerError() *PostLoginInternalServerError {

	return &PostLoginInternalServerError{}
}

// WithPayload adds the payload to the post login internal server error response
func (o *PostLoginInternalServerError) WithPayload(payload interface{}) *PostLoginInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post login internal server error response
func (o *PostLoginInternalServerError) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostLoginInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
