// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostRegisterOKCode is the HTTP code returned for type PostRegisterOK
const PostRegisterOKCode int = 200

/*PostRegisterOK OK

swagger:response postRegisterOK
*/
type PostRegisterOK struct {
}

// NewPostRegisterOK creates PostRegisterOK with default headers values
func NewPostRegisterOK() *PostRegisterOK {

	return &PostRegisterOK{}
}

// WriteResponse to the client
func (o *PostRegisterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostRegisterBadRequestCode is the HTTP code returned for type PostRegisterBadRequest
const PostRegisterBadRequestCode int = 400

/*PostRegisterBadRequest bad user request error

swagger:response postRegisterBadRequest
*/
type PostRegisterBadRequest struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewPostRegisterBadRequest creates PostRegisterBadRequest with default headers values
func NewPostRegisterBadRequest() *PostRegisterBadRequest {

	return &PostRegisterBadRequest{}
}

// WithPayload adds the payload to the post register bad request response
func (o *PostRegisterBadRequest) WithPayload(payload interface{}) *PostRegisterBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post register bad request response
func (o *PostRegisterBadRequest) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegisterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostRegisterInternalServerErrorCode is the HTTP code returned for type PostRegisterInternalServerError
const PostRegisterInternalServerErrorCode int = 500

/*PostRegisterInternalServerError internal server error

swagger:response postRegisterInternalServerError
*/
type PostRegisterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewPostRegisterInternalServerError creates PostRegisterInternalServerError with default headers values
func NewPostRegisterInternalServerError() *PostRegisterInternalServerError {

	return &PostRegisterInternalServerError{}
}

// WithPayload adds the payload to the post register internal server error response
func (o *PostRegisterInternalServerError) WithPayload(payload interface{}) *PostRegisterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post register internal server error response
func (o *PostRegisterInternalServerError) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegisterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
